export const SCREEN_KEYS = {
  GET_STARTED: "GET_STARTED",
  CREATE_ACCOUNT: "CREATE_ACCOUNT",
  LOG_IN: "LOG_IN",

  SELECT_ACTION: "SELECT_ACTION",
  MAIN_STACK: "MAIN_STACK",
  CATEGORIES: "CATEGORIES",
  SEARCH: "SEARCH"
};
